---
application_name: Claims System
business_name: My Company, LLC
business_address: 
domain: example.com
support_email: support@example.com
default_from_email: My App <no-reply@example.com>
background_job_processor: async
email_provider: 
personal_accounts: false
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
- acts_as_tenant
- rack-attack
- whenever
